server:
  port: 8888
spring:
  application:
    name: scm-saas-config-server
  cloud:
    config:
      label: dev
      server:
        git:
          default-label: dev
          uri: https://github.com/devrevo/SCM-SaaS-Config-Server.git
          username: <GITHUB_USERNAME_HERE>
          password: <GITHUB_TOKEN_HERE>
          clone-on-start: true